server:
  port: 8080

spring:
  application:
    name: auth-service

jwt:
  secret: ZDOAhj93i3I9mpNWIkOWRewrgchfgwrx
  expiration: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
