apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: shekharkumargupta/customer-service
        ports:
          - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
    selector:
      app: customers
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8083
        targetPort: 8083
