version: '1.1'
services:
  discovery:
    container_name: ms-discovery-service
    image: shekharkumargupta/discovery-service
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
      - microservices-net
    restart: unless-stopped


  gateway:
    container_name: ms-gateway-service
    image: shekharkumargupta/gateway-service
    ports:
      - 8222:8222
    expose:
      - 8222
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SERVER_PORT: 8222


  products:
    container_name: ms-product-service
    image: shekharkumargupta/product-service
    ports:
      - 8082:8082
    expose: 
      - 8082
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      - gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SERVER_PORT: 8082


  orders:
    container_name: ms-order-service
    image: shekharkumargupta/order-service
    ports:
      - 8081:8081
    expose: 
      - 8081
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      - products
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SERVER_PORT: 8081


  customers:
    container_name: ms-customer-service
    image: shekharkumargupta/customer-service
    ports:
      - 8083:8083
    expose:
      - 8083
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      - products
      - orders
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SERVER_PORT: 8083



networks:
  microservices-net:
    driver: bridge


