apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: discovery
        image: shekharkumargupta/gateway-service
        ports:
          - containerPort: 8222

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
    selector:
      app: gateway
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8222
        targetPort: 8222
