apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: shekharkumargupta/order-service
        ports:
          - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
    selector:
      app: orders
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
