apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: shekharkumargupta/product-service:latest
        ports:
          - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: products
spec:
    selector:
      app: products
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8082
        targetPort: 8082
