server:
  port: 8222

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: http://products:8082
          predicates:
            - Path=/products/**

        - id: order-route
          uri: http://orders:8081
          predicates:
            - Path=/orders/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

