server:
  port: 8222

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

        - id: order-route
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**

        - id: customer-route
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**

        - id: hello-route
          uri: http://localhost:8222
          predicates:
            - Path=/hello/**



#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true




