server:
  port: 8222

spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: http://products:8082
          predicates:
            - Path=/products/**

        - id: order-route
          uri: http://orders:8081
          predicates:
            - Path=/orders/**
            
        - id: customer-route
          uri: http://customers:8083
          predicates:
            - Path=/customers/**


eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
    register-with-eureka: true




