spring:
  application:
    name: order-service

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka



service:
  products-url: http://gateway:8222/products
