server:
  port: 8081

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger.html


spring:
  application:
    name: order-service


service:
  products-url: http://localhost:8082/products
