spring:
  application:
    name: order-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



service:
  gateway-url: http://localhost:8222
  product-url: PRODUCT-SERVICE/products
