spring:
  application:
    name: order-service

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



service:
  products-url: http://ms-product-service:8082/products
