server:
  port: 8082

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger.html

spring:
  application:
    name: product-service
#  cloud:
#    discovery:
#      enabled: false
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
