apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products-ctr
        image: shekharkumargupta/product-service:v1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
          - containerPort: 8082
          
          
