apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products-ctr
        image: shekharkumargupta/product-service:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
          - containerPort: 8082
          
          
